server:
  port: 8083
  servlet: 
    context-path: /study

spring:
  redis:
    host: 10.203.110.39
    port: 19000
    password:
    lettuce:   #连接池
      pool:
        max-active: 32    #连接池最大连接数（使用负值表示没有限制）
        max-wait: 300ms   #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 16      #连接池中的最大空闲连接
        min-idle: 8       #连接池中的最小空闲连接

  data:
    mongodb:
      custom:
        address: localhost
        port: 27017
        database: weibo
        replicaSet: 
        username: 
        password: 

  rocketmq:
      #profile: p1 按需要设置
      nameServerAddress:  10.203.106.26:9876;10.203.106.27:9876
      #ACL
      accessKey: RocketMQ
      secretKey: 12345678
      #是否需要追述 默认true
      enableMsgTrace: true
      producer:
        #按照需要设置
        group: demoApp
        #timeout
        sendMessageTimeout: 3000
        #触发压缩界限,默认4K
        compressMessageBodyThreshold: 4096
        #同步发送的最大重试次数
        retryTimesWhenSendFailed: 2
        #异步发送的最大重试次数
        retryTimesWhenSendAsyncFailed: 2
        #默认
        retryNextServer: true
        #消息大小上限
        maxMessageSize: 536870912
        
  datasource:
    #JDBC基本配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: 

    #数据源连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 2
    maxActive: 3
    maxWait: 60000                          #配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000      #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j                #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true

mybatis:
  mapper-locations: classpath:repository/*.xml
  